    'The Cero King',
    'Unohana',
    'The Fear',
    'Captain of the 6th Division',
    'Captain of the 2nd Division',
    'The Almighty',
    'Captain of the 12th Division',
    'Kenpachi',
    'The Tiger King',
    'Captain of the 9th Division',
    'The Bone King',
    'The Head Captain',
    'Captain of the 8th Division',
    'Captain of the 3rd Division',
    'Captain of the 7th Division',
